AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - app/controllers/application_controller.rb
    - app/controllers/user_controller.rb
    - Gemfile
    - Gemfile.lock
    - db/schema.rb
    - spec/main_spec.rb

Style/Documentation:
  Enabled: false

